<?php
$html = '<div class="div_non_summary_table" >';
$html .= '<table class="table table-striped">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th colspan="2" >Fundamental Data <i>(From Shareholder Report dated ' . date('M. d, Y', strtotime($get_fund_info[0]['assets_date'])) . ')</i></th>';
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td>Total Assets</td>';
$html .= '<td>$' . $get_fund_info[0]['total_assets_m'] . 'M</td>';
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td>Net Assets</td>';
$html .= '<td>$' . $get_fund_info[0]['net_assets_m'] . 'M</td>';
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td>Leverage <i>as % of Total Assets</i></td>';
$html .= '<td>' . $get_fund_info[0]['leverage_fundamental'] . '%</td>';
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td>Leverage Expense <i>as % of NAV</i></td>';
$html .= '<td>' . $get_fund_info[0]['lev_expense'] . '%</td>';
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td>Rel Lev Cost %</td>';
$html .= '<td>' . $get_fund_info[0]['rel_lev_expense'] . '%</td>';
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td>Leverage Type</td>';
$html .= '<td>' . $get_fund_info[0]['leverage_type'] . '</td>';
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td>Avg Net Expense Ratio</td>';
$html .= '<td>' . $get_fund_info[0]['exp_ratio_net_av'] . '%</td>';
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '</div>';
?>